version: '3.7'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn webapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    expose:
    - 8000
    env_file:
      - ./.env.prod
    depends_on: 
      - postgres
      - redis

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: 
      - ./.env.prod.db
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  
volumes:
  pgdata:
  redisdata: